apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: "global-jaeger-operator-bind"
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
  namespace: tracing
roleRef:
    kind: ClusterRole
    name: global-jaeger-operator
    apiGroup: rbac.authorization.k8s.io

