apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
    name: simple-jaeger
    namespace: tracing
spec:
    strategy: production
    collector:
        maxReplicas: 3
    storage:
        type: elasticsearch
        options:
            es:
                server-urls: http://elasticsearch-master.elastic:9200
                username: elastic
                password:
